/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * 
 * @author 2110010063
 */
 //Kelas AgendaPribadi adalah kelas utama untuk aplikasi Agenda Pribadi.
 //Ini mengatur GUI dan logika aplikasi untuk mengelola agenda pribadi.
 //Dapat menambahkan, mengedit, menghapus, mengimpor, dan mengekspor acara-acara.

public class AgendaPribadi extends javax.swing.JFrame {
    DefaultTableModel model;
    private int SelectedRow;//Baris yang dipilih dalam tabel
    private boolean isEditMode;// Apakah aplikasi berada dalam mode edit
    private int selectedRow;

    /**
     * Creates new form AgendaPribadi
     */
    public AgendaPribadi() {
        initComponents();
        // Menyiapkan kolom-kolom untuk tabel
        Object kolom [] = {"Acara","Date","Start Time","End Time"};
        Object data [][] = {}; 
        
        // Membuat model tabel dengan kolom yang telah disiapkan
        model = new DefaultTableModel(data, kolom);
        // Mengatur model tabel untuk tabel (tblAgenda)
        tblAgenda.setModel(model);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgenda = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tAcara = new javax.swing.JTextField();
        jDate = new com.toedter.calendar.JDateChooser();
        cbStart = new javax.swing.JComboBox<>();
        cbEnd = new javax.swing.JComboBox<>();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnImpor = new javax.swing.JButton();
        btnEkspor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Aplikasi Agenda Pribadi"));

        tblAgenda.setBackground(new java.awt.Color(204, 204, 255));
        tblAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Acara", "Date", "Start Time", "End Time"
            }
        ));
        tblAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAgendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAgenda);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        jLabel1.setText("Acara");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        jLabel2.setText("Date");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        jLabel3.setText("Start Time");

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        jLabel4.setText("End Time");

        tAcara.setBackground(new java.awt.Color(255, 204, 255));
        tAcara.setFont(new java.awt.Font("Segoe UI Light", 3, 13)); // NOI18N

        jDate.setBackground(new java.awt.Color(255, 204, 255));
        jDate.setDateFormatString("dd MM yyyy");

        cbStart.setBackground(new java.awt.Color(255, 204, 255));
        cbStart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05;00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00" }));

        cbEnd.setBackground(new java.awt.Color(255, 204, 255));
        cbEnd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05;00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00" }));

        btnEdit.setBackground(new java.awt.Color(204, 255, 153));
        btnEdit.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(204, 255, 153));
        btnHapus.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnHapus.setText("DELETE");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(204, 255, 153));
        btnBatal.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnBatal.setText("CANCEL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(204, 255, 204));
        btnSimpan.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnSimpan.setText("SAVE");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(204, 255, 204));
        btnKeluar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnKeluar.setText("EXIT");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnImpor.setBackground(new java.awt.Color(204, 255, 153));
        btnImpor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnImpor.setText("IMPORT");
        btnImpor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImporActionPerformed(evt);
            }
        });

        btnEkspor.setBackground(new java.awt.Color(204, 255, 153));
        btnEkspor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnEkspor.setText("EXPORT");
        btnEkspor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEksporActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSimpan)
                                    .addComponent(btnKeluar))
                                .addGap(147, 147, 147))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tAcara, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnEdit)
                                            .addGap(133, 133, 133)
                                            .addComponent(btnImpor))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnBatal)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnEkspor)))
                                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 40, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tAcara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit)
                            .addComponent(btnImpor)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnHapus)))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(btnBatal)
                            .addComponent(btnEkspor)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnSimpan)
                        .addGap(43, 43, 43)
                        .addComponent(btnKeluar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    String Acara = tAcara.getText();
        Date Date = jDate.getDate();
        String StartTime = cbStart.getSelectedItem().toString();
        String EndTime = cbEnd.getSelectedItem().toString();
     
     //Mengecek nilai yang di input
     if (tAcara.getText().equals("")) {
         JOptionPane.showMessageDialog(null, "Lengkapi Data Yang Kosong..!",
                    "Error",JOptionPane.WARNING_MESSAGE);
          }else{
     //Menambahkan data ke dalam row
        DefaultTableModel model = (DefaultTableModel) tblAgenda.getModel();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
         model.addRow(new Object[] {Acara, Date, StartTime, EndTime});
         JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");

     //Membersihkan field setelah data berhasil terinput
     tAcara.setText("");
     jDate.setDate(null);
     cbStart.setSelectedIndex(0);
     cbEnd.setSelectedIndex(0);
     }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
     // Silahkan mengecek apakah ada baris yang dipilih
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang mau diubah", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Mengambil data dari fields
        String Acara = tAcara.getText();
        Date Date = jDate.getDate();
        String StartTime = cbStart.getSelectedItem().toString();
        String EndTime = cbEnd.getSelectedItem().toString();
        
         // Validasi inputan yang tidak ada
        if (Acara.isEmpty()) {
            JOptionPane.showMessageDialog(this, "DiHarapkan lengkapi semua field", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Melakukan Update data pada baris yang dipilih
           tblAgenda.setValueAt(Acara, selectedRow, 0);
           tblAgenda.setValueAt(Date, selectedRow, 1);
           tblAgenda.setValueAt(StartTime, selectedRow, 2);
           tblAgenda.setValueAt(EndTime, selectedRow, 3);

        // Membersihkan input field sesudah data diubah
            tAcara.setText("");
            jDate.setDate(null);
            cbStart.setSelectedItem("");
            cbEnd.setSelectedItem("");
        
        // Melakukan reset pemilihan baris pada tabel
        tblAgenda.clearSelection();
        
        // Untuk mengembalikan ke mode tambah dan mengaktifkan kembali tombol tambah
        isEditMode = false;
        btnSimpan.setEnabled(true);
        
        // Menampilkan JOptionPane untuk memberi pesan bahwa data sudah berhasil diubah
        JOptionPane.showMessageDialog(this, "Data Berhasil Diubah", "Berhasil", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // Fungsi untuk keluar dari aplikasi
        String tanya = "Are you sure want to exit?";
        boolean yakin = JOptionPane.showConfirmDialog(rootPane, tanya) == 
                JOptionPane.YES_OPTION;
        if(yakin){
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
      // Fungsi untuk membatalkan aksi
      tAcara.setText(""); // Mengosongkan teks field Acara
      jDate.setDate(null); // Menghapus tanggal yang dipilih di JDateChooser
      cbStart.setSelectedIndex(0); // Mengatur pilihan awal di JComboBox untuk waktu mulai
      cbEnd.setSelectedIndex(0); // Mengatur pilihan awal di JComboBox untuk waktu selesai
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
     // Menghapus Data pada Tabel
          
          if(tblAgenda.getSelectedRowCount() == 1){
              // Jika satu baris sudah dipilih makan akan terhapus
              model.removeRow(tblAgenda.getSelectedRow());
              
              JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
          }else{
              if(tblAgenda.getRowCount() == 0){
                  // Jika data kosong maka akan muncul pesan 
                  JOptionPane.showMessageDialog(this, "Tabel Datanya Kosong");
              }else{
                  // Jika Tidak Kosong tetapi tidak ada pada baris yang akan dipilih maka muncul pesan
                  JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Yang Mau Dihapus");
              }
          }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEksporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEksporActionPerformed
    // Fungsi untuk mengekspor data ke file
    try{
            BufferedWriter out = new BufferedWriter (new FileWriter("AgendaPribadi.text"));
            
            for(int i = 0; i < tblAgenda.getRowCount(); i++){ // rows
                for (int j = 0; j < tblAgenda.getColumnCount(); j++){ // columns
                    out.write(tblAgenda.getValueAt(i, j).toString()+"/ ");
                }
                out.newLine();
            }            
            JOptionPane.showMessageDialog(null, "Berhasil Diexport Kedalam File");
            
            out.close();
        }catch (Exception e){
            System.err.println("Error: "+e.getMessage());
    }       
    }//GEN-LAST:event_btnEksporActionPerformed

    private void btnImporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImporActionPerformed
    // Mendefinisikan path file yang akan diimpor 
    String filePath = "AgendaPribadi.text";
    File file = new File(filePath);
     try {
    // Membuka file untuk dibaca
    FileReader fr = new FileReader(file);    
    BufferedReader br = new BufferedReader(fr);
    
    // Mendapatkan model tabel yang digunakan
    DefaultTableModel model = (DefaultTableModel) tblAgenda.getModel(); 
    Object[] lines = br.lines().toArray();
    
    // Membaca setiap baris dari file dan menambahkannya ke dalam tabel
    for(int i = 0; i < lines.length; i++ ){
        String[] row = lines[i].toString().split("/ ");
        model.addRow(row);
    }
} catch (IOException e) {
    e.printStackTrace();
}

    }//GEN-LAST:event_btnImporActionPerformed

    private void tblAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAgendaMouseClicked
    // Untuk mendapatkan baris yang dipilih saat mouse di-klik pada tabel
         selectedRow = tblAgenda.getSelectedRow();
    // Untuk menampilkan data dari baris yang dipilih pada TextField
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) tblAgenda.getModel();
            tAcara.setText(model.getValueAt(selectedRow, 0).toString());
            jDate.setDate((Date) model.getValueAt(selectedRow, 1));
            cbStart.setSelectedItem(model.getValueAt(selectedRow, 2).toString());
            cbEnd.setSelectedItem(model.getValueAt(selectedRow, 3).toString());
        }
    }//GEN-LAST:event_tblAgendaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaPribadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaPribadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaPribadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaPribadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaPribadi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEkspor;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnImpor;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbEnd;
    private javax.swing.JComboBox<String> cbStart;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tAcara;
    private javax.swing.JTable tblAgenda;
    // End of variables declaration//GEN-END:variables

    


    
}
